### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by younesslam**
Tikrank is no longer working, so I've added Countik as a replacement because it does the same thing.

### CODE REVIEW

**Comment by cipher387** [comment]
Countik don't work too! (tested this site in Google Chrome)

**Comment by younesslam** [comment]
doesn't work how? It's working for me as described.

**Comment by cipher387** [comment]
A couple of hours ago it wouldn't give any results after entering the name of the account. It is now also very slow to open

**Comment by younesslam** [comment]
I see. It's not very good.

**Pull request closed without merging**
